### PR TITLE
Add "sukebei.nyaa.si" plugin + icon fix for "nyaa.si"

### LINKED ISSUE #6: add nyaa sukebei support
https://sukebei.nyaa.net
https://sukebei.nyaa.si

### PR DESCRIPTION
**Pull request by Obegg**
Cloned the original "[nyaasi.py](https://github.com/MadeOfMagicAndWires/qBit-plugins/blob/master/engines/nyaasi.py)", edited a few lines and now "sukebei.nyaa.si" is working.
Added an icon to "sukebei.nyaa.si".
And fixed the icon for the original "nyaasi".

You might wanna add "sukebei.nyaa.si.py" to the [Unofficial search plugins](https://github.com/qbittorrent/search-plugins/wiki/Unofficial-search-plugins) (I leave it to you, the existing one there doesn't work)

Fixes https://github.com/MadeOfMagicAndWires/qBit-plugins/issues/6

### CODE REVIEW

**Comment by MadeOfMagicAndWires** [comment]
Sorry about this; this PR somehow slipped by me; I've been rather distracted by health related issues. 

I personally never really bothered with creating a sukebei plugin, as one was already available, but as I understand that plugin stopped working since, if you'd like me to merge this PR I still can.

**Comment by Obegg** [comment]
Never mind, I use [Jackett ](https://github.com/Jackett/Jackett)now, it has everything I need.

**Comment by vt-idiot** [comment]
...I should have looked at the pull requests before [reinventing the wheel](https://github.com/vt-idiot/qBit-SukebeiNyaa-plugin).

Works great though! Thank you both. Looking closely at this PR, it seems that categories were not properly mapped to sukebei's. @MadeOfMagicAndWires if you want to use my implementation, feel free to. I'm a github newbie, not sure if I would have to open a PR from my fork or if you can do so.

**Comment by vt-idiot** [comment]
Actually, I went gungho with deletions and re-writing the license/readme. I can re-fork it and just upload the new script + icon if you do want me to make a PR.

**Comment by MadeOfMagicAndWires** [comment]
@vt-idiot a separate PR would be great thanks

**Pull request closed without merging**
